# Generated by Django 3.0.9 on 2020-08-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CS_quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('a', models.CharField(max_length=256)),
                ('b', models.CharField(max_length=256)),
                ('c', models.CharField(max_length=256)),
                ('d', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('quiz_type', models.CharField(max_length=64)),
                ('user_correct', models.IntegerField()),
                ('user_wrong', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('dateTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_result_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('quiz_type', models.CharField(max_length=64)),
                ('q_no', models.IntegerField()),
                ('selected_value', models.CharField(blank='true', default='default', max_length=64)),
                ('result', models.CharField(max_length=64)),
                ('usr_correct', models.IntegerField()),
                ('usr_wrong', models.IntegerField()),
                ('dateTime', models.DateField()),
            ],
        ),
    ]
