# Generated by Django 3.0.8 on 2020-07-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=64)),
                ('a', models.CharField(max_length=64)),
                ('b', models.CharField(max_length=64)),
                ('c', models.CharField(max_length=64)),
                ('d', models.CharField(max_length=64)),
                ('answer', models.CharField(max_length=64)),
            ],
        ),
    ]
