# Generated by Django 3.0.8 on 2020-07-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizBox', '0003_quiz_result_table_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('quiz_type', models.CharField(max_length=64)),
                ('usr_correct', models.IntegerField()),
                ('usr_worng', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('dateTime', models.DateField()),
            ],
        ),
    ]
