# Generated by Django 3.0.8 on 2020-07-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizBox', '0004_quiz_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_dashboard',
            old_name='usr_correct',
            new_name='user_correct',
        ),
        migrations.RenameField(
            model_name='quiz_dashboard',
            old_name='usr_worng',
            new_name='user_worng',
        ),
    ]
