# Generated by Django 3.0.8 on 2020-07-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizBox', '0005_auto_20200726_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_dashboard',
            old_name='user_worng',
            new_name='user_wrong',
        ),
        migrations.RenameField(
            model_name='quiz_result_table',
            old_name='usr_worng',
            new_name='usr_wrong',
        ),
    ]
